# Generated by Django 5.2.15 on 2026-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='deadline',
            new_name='end_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
