# Generated by Django 5.2.15 on 2026-06-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_updated_at_messagereaction'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='subproject',
        ),
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='group.group'),
        ),
    ]
