# Generated by Django 5.2.15 on 2026-06-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_subproject_conversation_group'),
        ('task', '0007_task_forwarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='task.task'),
        ),
    ]
