# Generated by Django 5.2.15 on 2026-06-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_task'),
        ('task', '0007_task_forwarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='task.task'),
        ),
    ]
