# Generated by Django 5.2.15 on 2026-06-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
    ]
