# Generated by Django 5.2.15 on 2026-06-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('task', '0003_task_is_routine_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.subproject'),
        ),
    ]
