# Generated by Django 5.2.15 on 2026-06-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_forwarded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskroutine',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='task.task'),
        ),
    ]
