# Generated by Django 5.2.15 on 2026-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_checklist_task_alter_taskattachment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
