# Generated by Django 5.2.15 on 2026-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='tasks/voice/'),
        ),
    ]
