# Generated by Django 5.2.15 on 2026-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/subproject'),
        ),
    ]
