# Generated by Django 5.2.15 on 2026-06-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_subproject_avatar'),
        ('task', '0011_alter_task_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subprojects', to='task.status'),
            preserve_default=False,
        ),
    ]
